# Generated by Django 4.1.3 on 2022-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintservice',
            name='base_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
