# Generated by Django 4.1.3 on 2022-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_camopattern_friendly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponplatform',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='weaponsystem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
