# Generated by Django 4.1.3 on 2022-11-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_rename_delivery_method_cost_deliverymethod_cost_and_more'),
        ('checkout', '0003_rename_original_bag_order_original_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliverymethod', to='basket.deliverymethod'),
        ),
    ]
