# Generated by Django 4.1.3 on 2022-11-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='delivery_method_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='delivery_method_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
