# Generated by Django 4.1.3 on 2022-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_full_name'),
        ('products', '0002_brand_alter_category_options_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='profiles.userprofile'),
        ),
    ]
